# COM400 Week 6 Lab: Matrices

## Exercise 1 

Let

$\mathbf{A} = \begin{bmatrix} 1 & 4 \\ 3 & -1 \\ 0 & 7 \end{bmatrix} \qquad \mathbf{B} = \begin{bmatrix} 2 & 1 & 3 \\ -5 & 6 & 1 \end{bmatrix} \qquad \mathbf{C} = \begin{bmatrix} -3 \\ 9 \\ 0 \\ 9 \end{bmatrix} \qquad \mathbf{D} = \begin{bmatrix} 2 & 1 & -3 & 0\\ -3 & 1 & 5 & 2 \\ 1 & -1 & 8 & 4 \\ 2 & 4 & -3 & -1 \end{bmatrix}$

(a) Represent each matrix in Python.

In [1]:
# Imports NumPy
import numpy as np

# Creates matricies
A = np.array([[1,4],[3,-1],[0,7]])
B = np.array([[2,1,3],[-5,6,1]])
C = np.array([[-3],[9],[0],[9]])
D = np.array([[2,1,-3,0],[-3,1,5,2],[1,-1,8,4],[2,4,-3,-1]])

# Displays matrices
print("A = \n", A)
print("B = \n", B)
print("C = \n", C)
print("D = \n", D)

A = 
 [[ 1  4]
 [ 3 -1]
 [ 0  7]]
B = 
 [[ 2  1  3]
 [-5  6  1]]
C = 
 [[-3]
 [ 9]
 [ 0]
 [ 9]]
D = 
 [[ 2  1 -3  0]
 [-3  1  5  2]
 [ 1 -1  8  4]
 [ 2  4 -3 -1]]


(b) Display the order of each matrix.

In [2]:
print("A has the order", A.shape)
print("B has the order", B.shape)
print("C has the order", C.shape)
print("D has the order", D.shape)

A has the order (3, 2)
B has the order (2, 3)
C has the order (4, 1)
D has the order (4, 4)


(c) Display the transpose of each matrix.

In [3]:
print("Transpose of A\n", A.T)
print("Transpose of B\n", B.T)
print("Transpose of C\n", C.T)
print("Transpose of D\n", D.T)

Transpose of A
 [[ 1  3  0]
 [ 4 -1  7]]
Transpose of B
 [[ 2 -5]
 [ 1  6]
 [ 3  1]]
Transpose of C
 [[-3  9  0  9]]
Transpose of D
 [[ 2 -3  1  2]
 [ 1  1 -1  4]
 [-3  5  8 -3]
 [ 0  2  4 -1]]


(d) What is $\mathbf{A} + \mathbf{B}^T$?

In [4]:
print("A + B^T =\n", A+B.T)

A + B^T =
 [[ 3 -1]
 [ 4  5]
 [ 3  8]]


(e) What is $\mathbf{D}^T - 2\mathbf{D}$?

In [5]:
print("D^T - 2D =\n", D.T-(2*D))

D^T - 2D =
 [[ -2  -5   7   2]
 [  7  -1 -11   0]
 [ -5   7  -8 -11]
 [ -4  -6  10   1]]


(f) Print out:
- the value of $b_{22}$
- the value of $d_{12}$
- the last row of $\mathbf{A}$
- the third column of $\mathbf{D}$

In [6]:
print("b22 =", B[1,1])
print("d12 =", D[0,1])
print("Last row of A =", A[-1,:])
print("Third column of D =\n", D[:,2])

b22 = 6
d12 = 1
Last row of A = [0 7]
Third column of D =
 [-3  5  8 -3]


(g) The sum of elements along the leading diagonal of a square matrix is called the **trace**. Calculate the trace of $\mathbf{D}$ by:
- accessing the values of the relevant elements and summing them up
- using the `trace` funcion from `numpy`

In [7]:
# Declares sum variable
sum = 0
# Runs for each row in D
for i in range(D.shape[0]):
    # Adds needed value to sum
    sum += D[i,i]
# Outputs the result
print("The trace of D:")
print("\tfrom loop =", sum)
print("\tfrom NumPy =", np.trace(D))

The trace of D:
	from loop = 10
	from NumPy = 10


## Exercise 2
If possible carry out the following matrix multiplications based on the matrices from Exercise 1.

In [8]:
def multiplyMatrices(X, Y):
    # Returns error if matrices cannot be multiplied together
    if X.shape[1] != Y.shape[0]:
        return "Matricies cannot be multiplied together"
    # Otherwise returns the calculation
    else:
        return X @ Y

(a) $\mathbf{BD}$

In [9]:
print("BD =\n", multiplyMatrices(B, D))

BD =
 Matricies cannot be multiplied together


(b) $\mathbf{D}^T\mathbf{C}$

In [10]:
print("(D^T)C =\n", multiplyMatrices(D.T, C))

(D^T)C =
 [[-15]
 [ 42]
 [ 27]
 [  9]]


(c) $\mathbf{CC}^T$

In [11]:
print("C(C^T) =\n", multiplyMatrices(C, C.T))

C(C^T) =
 [[  9 -27   0 -27]
 [-27  81   0  81]
 [  0   0   0   0]
 [-27  81   0  81]]


(d) $\mathbf{C}^T\mathbf{C}$

In [12]:
print("(C^T)C =\n", multiplyMatrices(C.T, C))

(C^T)C =
 [[171]]


(d) $\mathbf{D}^2$, $\mathbf{D}^3$, $\mathbf{D}^4$, $\mathbf{D}^5$

In [13]:
print("D^2 =\n", np.linalg.matrix_power(D, 2))
print("D^3 =\n", np.linalg.matrix_power(D, 3))
print("D^4 =\n", np.linalg.matrix_power(D, 4))
print("D^5 =\n", np.linalg.matrix_power(D, 5))

D^2 =
 [[ -2   6 -25 -10]
 [  0   1  48  20]
 [ 21   8  44  26]
 [-13   5  -7  -3]]
D^3 =
 [[ -67  -11 -134  -78]
 [  85   33  329  174]
 [ 114   89  251  166]
 [ -54  -13   17  -15]]
D^4 =
 [[-391 -256 -692 -480]
 [ 748  485 2020 1208]
 [ 544  616 1613 1016]
 [ -82 -144  278   57]]
D^5 =
 [[-1666 -1875 -4203 -2800]
 [ 4477  4045 12717  7842]
 [ 2885  3611 11304  6668]
 [  660  -276  1579   767]]


(e) Show that $\mathbf{AB} \neq \mathbf{BA}$

In [14]:
print("AB =\n", multiplyMatrices(A, B))
print("BA =\n", multiplyMatrices(B, A))
print("Therefore AB ≠ BA")

AB =
 [[-18  25   7]
 [ 11  -3   8]
 [-35  42   7]]
BA =
 [[  5  28]
 [ 13 -19]]
Therefore AB ≠ BA


(f) Show that $(\mathbf{AB})^T = \mathbf{B}^T\mathbf{A}^T$

In [15]:
print("(AB)^T =\n", multiplyMatrices(A, B).T)
print("(B^T)(A^T) =\n", multiplyMatrices(B.T, A.T))
print("Therefore (AB)^T = (B^T)(A^T)")

(AB)^T =
 [[-18  11 -35]
 [ 25  -3  42]
 [  7   8   7]]
(B^T)(A^T) =
 [[-18  11 -35]
 [ 25  -3  42]
 [  7   8   7]]
Therefore (AB)^T = (B^T)(A^T)


(g) Let 

$E = \begin{bmatrix} 2 & 2 \\ 1 & 5 \\ 4 & 3 \end{bmatrix}$

Show that $\mathbf{A}(\mathbf{BE}) = (\mathbf{AB})\mathbf{E}$

In [16]:
E = np.array([[2,2],[1,5],[4,3]])

print("A(BE) =\n", multiplyMatrices(A, multiplyMatrices(B, E)))
print("(AB)E =\n", multiplyMatrices(multiplyMatrices(A, B), E))
print("Therefore A(BE) = (AB)E")

A(BE) =
 [[ 17 110]
 [ 51  31]
 [  0 161]]
(AB)E =
 [[ 17 110]
 [ 51  31]
 [  0 161]]
Therefore A(BE) = (AB)E


## Exercise 3 
Show how you would create the following matrices using special functions rather than having to list all the values in your code. 

(a) $$\mathbf{G} = \begin{pmatrix} 7 & 7 & 7 & 7 & 7\\ 7 & 7 & 7 & 7 & 7\\ 7 & 7 & 7 & 7 & 7\\ 7 & 7 & 7 & 7 & 7\\ 7 & 7 & 7 & 7 & 7\end{pmatrix}$$

In [17]:
G = 7 * np.ones((5,5))
print("G =\n", G)

G =
 [[7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]
 [7. 7. 7. 7. 7.]]


(b) $$\mathbf{H} = \begin{pmatrix} 
2 & -1 & -1 & -1 & -1 & -1 & -1 & -1 & -1 & -1\\ 
-1 & 2 & -1 & -1 & -1 & -1 & -1 & -1 & -1 & -1\\
-1 & -1 & 2 & -1 & -1 & -1 & -1 & -1 & -1 & -1\\
-1 & -1 & -1 & 2 & -1 & -1 & -1 & -1 & -1 & -1\\
-1 & -1 & -1 & -1 & 2 & -1 & -1 & -1 & -1 & -1\\
-1 & -1 & -1 & -1 & -1 & 2 & -1 & -1 & -1 & -1\\
-1 & -1 & -1 & -1 & -1 & -1 & 2 & -1 & -1 & -1\\
-1 & -1 & -1 & -1 & -1 & -1 & -1 & 2 & -1 & -1\\
-1 & -1 & -1 & -1 & -1 & -1 & -1 & -1 & 2 & -1\\
-1 & -1 & -1 & -1 & -1 & -1 & -1 & -1 & -1 & 2\\
\end{pmatrix}$$

In [18]:
H = (3 * np.eye(10)) - np.ones((10,10))
print("H =\n", H)

H =
 [[ 2. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1.  2. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1.  2. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1.  2. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1.  2. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1.  2. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1.  2. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1.  2. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1.  2. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1.  2.]]


(c) $$\mathbf{K} = \begin{pmatrix} 
2 & 1 & 0 & 0 & 0 & 0\\ 
1 & 2 & 1 & 0 & 0 & 0\\
0 & 1 & 2 & 1 & 0 & 0\\
0 & 0 & 1 & 2 & 1 & 0\\
0 & 0 & 0 & 1 & 2 & 1\\
0 & 0 & 0 & 0 & 1 & 2\\
\end{pmatrix}$$

In [19]:
K = np.eye(6) + np.diag(np.array([1,1,1,1,1,1])) + np.diag(np.array([1,1,1,1,1]), k=1) + np.diag(np.array([1,1,1,1,1]), k=-1)
print("K =\n", K)

K =
 [[2. 1. 0. 0. 0. 0.]
 [1. 2. 1. 0. 0. 0.]
 [0. 1. 2. 1. 0. 0.]
 [0. 0. 1. 2. 1. 0.]
 [0. 0. 0. 1. 2. 1.]
 [0. 0. 0. 0. 1. 2.]]


## Exercise 4
(a) Find the determinant of each of the matrices in Exercise 3.

In [20]:
print("Determinant of G =", np.linalg.det(G))
print("Determinant of H =", np.linalg.det(H))
print("Determinant of K =", np.linalg.det(K))

Determinant of G = 0.0
Determinant of H = -137781.00000000003
Determinant of K = 6.999999999999998


(b) If possible, find the inverse of each matrix in Exercise 3.

In [21]:
def findInverse(X):
    # Returns error if determinant is 0
    if np.linalg.det(X) == 0.0:
        return "Impossible"
    # Otherwise return the inverse
    else:
        return np.linalg.inv(X)

print("The inverse of G is\n", findInverse(G))
print("The inverse of H is\n", findInverse(H))
print("The inverse of K is\n", findInverse(K))

The inverse of G is
 Impossible
The inverse of H is
 [[ 0.28571429 -0.04761905 -0.04761905 -0.04761905 -0.04761905 -0.04761905
  -0.04761905 -0.04761905 -0.04761905 -0.04761905]
 [-0.04761905  0.28571429 -0.04761905 -0.04761905 -0.04761905 -0.04761905
  -0.04761905 -0.04761905 -0.04761905 -0.04761905]
 [-0.04761905 -0.04761905  0.28571429 -0.04761905 -0.04761905 -0.04761905
  -0.04761905 -0.04761905 -0.04761905 -0.04761905]
 [-0.04761905 -0.04761905 -0.04761905  0.28571429 -0.04761905 -0.04761905
  -0.04761905 -0.04761905 -0.04761905 -0.04761905]
 [-0.04761905 -0.04761905 -0.04761905 -0.04761905  0.28571429 -0.04761905
  -0.04761905 -0.04761905 -0.04761905 -0.04761905]
 [-0.04761905 -0.04761905 -0.04761905 -0.04761905 -0.04761905  0.28571429
  -0.04761905 -0.04761905 -0.04761905 -0.04761905]
 [-0.04761905 -0.04761905 -0.04761905 -0.04761905 -0.04761905 -0.04761905
   0.28571429 -0.04761905 -0.04761905 -0.04761905]
 [-0.04761905 -0.04761905 -0.04761905 -0.04761905 -0.04761905 -0.0476190

## Exercise 5
(a) Solve the following set of linear equations for $x$, $y$ and $z$:

\begin{align}
x + y + z & = 3 \\
2x  + 7y + 2z & = 15 \\
-3x + 4y + z & = 0
\end{align}

In [22]:
# Declares matricies for known values
M = np.array([[1,1,1],[2,7,2],[-3,4,1]])
N = np.array([[3,15,0]]).T
# Finds x, y and z
O = np.linalg.solve(M, N)

# Prints out the results
print("M =\n", M)
print("N =\n", N)
print("Therefore O =\n", O)
print("\nSo the solution is")
print("\tx =", O[0,0])
print("\ty =", O[1,0])
print("\tz =", O[2,0])

M =
 [[ 1  1  1]
 [ 2  7  2]
 [-3  4  1]]
N =
 [[ 3]
 [15]
 [ 0]]
Therefore O =
 [[ 2.1]
 [ 1.8]
 [-0.9]]

So the solution is
	x = 2.1
	y = 1.8
	z = -0.8999999999999995


(b) Suppose a cinema ticket costs £9 for an adult and £5 for a child. Suppose in one hour, 34 tickets sold for £290. 

Represent this as a set of simultaneous equations, and use matrices to determine how many adult tickets and child tickets were sold.


\begin{align}
x9 + y5 = 290 \\
x + y = 34
\end{align}

In [23]:
# Declares matricies for known values
P = np.array([[9,5],[1,1]])
Q = np.array([[290,34]]).T
# Finds x and y
R = np.linalg.solve(P, Q)

# Prints out the results
print("P =\n", P)
print("Q =\n", Q)
print("Therefore R =\n", R)
print("\nSo the solution is")
print("\tx =", R[0,0])
print("\ty =", R[1,0])

P =
 [[9 5]
 [1 1]]
Q =
 [[290]
 [ 34]]
Therefore R =
 [[30.]
 [ 4.]]

So the solution is
	x = 30.0
	y = 4.0000000000000036
